# Generated by Django 3.2.3 on 2022-01-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_remove_category_friendly_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.category",
            ),
        ),
    ]
