# Generated by Django 3.2.3 on 2022-01-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_ategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ategory',
            new_name='category',
        ),
    ]
